#!/bin/sh

### BEGINN INIT INFO
# Provides:          uwsgi-manager
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts all uWSGI applications using uwsgi-manager
# Description:       starts all uWSGI applications using uwsgi-manager
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin/
DAEMON=/usr/local/bin/uwsgi-manager
DESC="uWSGI applications"
NAME=uwsgi

test -x $DAEMON || exit 0

case "$1" in
  start)
        echo -n "Starting $DESC: "
        $DAEMON -a
        echo $NAME
        ;;
  stop)
        echo -n "Stopping $DESC: "
        $DAEMON -A
        echo $NAME
        ;;
  reload)
        echo -n "Reloading $DESC"
        $DAEMON -w
        echo $NAME
        ;;
  force-reload)
        echo -n "Force reloading $DESC"
        $DAEMON -B
        echo $NAME
       ;;
  restart)
        echo -n "Restarting $DESC: "
        $DAEMON -W
        echo $NAME
        ;;
  status) 
        $DAEMON -l
        ;;
      *)  
            N=/etc/init.d/$NAME
            echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
            exit 1
            ;;
    esac
    exit 0

